=== Jo-dle/E2_UF2217_Joel/Controladores/c.empresa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--Restricciones Personalizadas-->
    <xs:simpleType name="CEDType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="CCDType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="CDDType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="sexoType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[H]|[M]"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="departamentoType">
        <xs:restriction base="xs:string">
            <xs:pattern value="Limpieza|Producción|Contabilidad|Mantenimiento"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="codigoPostType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{5}"/>
        </xs:restriction>
    </xs:simpleType>
    <!--Elemento Raíz-->
    <xs:element name="registroPersonal">
        <xs:complexType>
            <xs:sequence>
                <!--Empleados-->
                <xs:element name="empleados">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="empleado" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="sexo" type="sexoType"/>
                                        <xs:element name="contacto">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="email"/>
                                                    <xs:element name="telefono"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="departamento" type="departamentoType"/>
                                    </xs:sequence>
                                    <xs:attribute name="CED" type="CEDType" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <!--Consultores-->
                <xs:element name="consultores">
                    <xs:complexType>
                        <xs:sequence>
                         <xs:element name="consultor" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                 <xs:element name="nombre" type="xs:string"/>
                                 <xs:element name="sexo" type="sexoType"/>
                                    <xs:element name="contacto">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="email" type="xs:string"/>
                                                <xs:element name="telefono" type="xs:string"/>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                 <xs:element name="departamento" type="departamentoType"/>
                                 <xs:element name="empresaExterna" type="xs:string"/>
                                </xs:sequence>
                                <xs:attribute name="CCD" type="CCDType" use="required"/>
                           </xs:complexType>
                         </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <!--Departamentos-->
                <xs:element name="departamentos">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="departamento" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="director" type="xs:string"/>
                        <xs:element name="empleados">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="empleado" maxOccurs="unbounded"/>
                                </xs:sequence>
                            </xs:complexType>  
                        </xs:element>
                        <xs:element name="direccion">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="calle" type="xs:string"/>
                                    <xs:element name="ciudad" type="xs:string"/>
                                    <xs:element name="codigoPostal" type="codigoPostType"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="CDD" type="CDDType" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Jo-dle/E2_UF2217_Joel/Vistas/v.empresa.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../Estilo/e.empresa.xsl"?>
<registroPersonal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Controladores/c.empresa.xsd">

<empleados>

    <empleado CED="C01">
        <nombre>Alberto</nombre>
        <sexo>H</sexo>
        <contacto>

            <email>Alberto@gmail.com</email>
            <telefono>928112233</telefono>
        </contacto>

        <departamento>Contabilidad</departamento>
    </empleado>

    <empleado CED="M01">
        <nombre>Juan</nombre>
        <sexo>H</sexo>
        <contacto>

            <email>Juan@gmail.com</email>
            <telefono>928223344</telefono>
        </contacto>

        <departamento>Mantenimiento</departamento>
    </empleado>

    <empleado CED="C02">
        <nombre>María</nombre>
        <sexo>M</sexo>
        <contacto>

            <email>María@gmail.com</email>
            <telefono>928334455</telefono>
        </contacto>

        <departamento>Contabilidad</departamento>
    </empleado>

    <empleado CED="P01">
        <nombre>Lúcas</nombre>
        <sexo>H</sexo>
        <contacto>

            <email>Lúcas@gmail.com</email>
            <telefono>928556677</telefono>
        </contacto>

        <departamento>Producción</departamento>
    </empleado>

    <empleado CED="C03">
        <nombre>Juani</nombre>
        <sexo>M</sexo>
        <contacto>

            <email>Juani@gmail.com</email>
            <telefono>928667788</telefono>
        </contacto>

        <departamento>Contabilidad</departamento>
    </empleado>

    <empleado CED="L01">
        <nombre>Martín</nombre>
        <sexo>H</sexo>
        <contacto>

            <email>Martín@gmail.com</email>
            <telefono>928778899</telefono>
        </contacto>

        <departamento>Limpieza</departamento>
    </empleado>

    <empleado CED="M02">
        <nombre>Neftalí</nombre>
        <sexo>H</sexo>
        <contacto>

            <email>NeftalíDeJesusEspino_123@gmail.com</email>
            <telefono>636539657</telefono>
        </contacto>

        <departamento>Mantenimiento</departamento>
    </empleado>

    <empleado CED="M03">
        <nombre>Constantino</nombre>
        <sexo>H</sexo>
        <contacto>

            <email>Lantigua21@gmail.com</email>
            <telefono>666666666</telefono>
        </contacto>

        <departamento>Mantenimiento</departamento>
    </empleado>

    <empleado CED="L02">
        <nombre>Rigoberto</nombre>
        <sexo>H</sexo>
        <contacto>

            <email>Rigoberto@gmail.com</email>
            <telefono>928889911</telefono>
        </contacto>

        <departamento>Limpieza</departamento>
    </empleado>

    <empleado CED="L03">
        <nombre>Ana</nombre>
        <sexo>M</sexo>
        <contacto>

            <email>Ana@gmail.com</email>
            <telefono>928223344</telefono>
        </contacto>

        <departamento>Limpieza</departamento>
    </empleado>
    </empleados>
    
 <consultores>
    <consultor CCD="L01">
        <nombre>Manuel</nombre>
        <sexo>H</sexo>
        <contacto>
            <email>Manuel@gmail.com</email>
            <telefono>611116161</telefono>
        </contacto>
        <departamento>Limpieza</departamento>
        <empresaExterna>Milipili.SA</empresaExterna>
    </consultor>

     <consultor CCD="M01">
        <nombre>Isabel</nombre>
        <sexo>M</sexo>
        <contacto>
            <email>Isabel@gmail.com</email>
            <telefono>622226626</telefono>
        </contacto>
        <departamento>Mantenimiento</departamento>
        <empresaExterna>PCarreglos</empresaExterna>
    </consultor>

     <consultor CCD="P01">
        <nombre>Carlos</nombre>
        <sexo>H</sexo>
        <contacto>
            <email>Carlos@gmail.com</email>
            <telefono>633336636</telefono>
        </contacto>
        <departamento>Producción</departamento>
        <empresaExterna>Lentes Y Cámaras</empresaExterna>
    </consultor>

     <consultor CCD="M02">
        <nombre>Amenariel</nombre>
        <sexo>H</sexo>
        <contacto>
            <email>Amenariel@gmail.com</email>
            <telefono>644446646</telefono>
        </contacto>
        <departamento>Mantenimiento</departamento>
        <empresaExterna>La informática Y Tú</empresaExterna>
    </consultor>

     <consultor CCD="C01">
        <nombre>Isobel</nombre>
        <sexo>M</sexo>
        <contacto>
            <email>Isobel@gmail.com</email>
            <telefono>655556656</telefono>
        </contacto>
        <departamento>Contabilidad</departamento>
        <empresaExterna>Números.SL</empresaExterna>
    </consultor>

     <consultor CCD="L02">
        <nombre>Emueto</nombre>
        <sexo>H</sexo>
        <contacto>
            <email>Emueto@gmail.com</email>
            <telefono>112233699</telefono>
        </contacto>
        <departamento>Limpieza</departamento>
        <empresaExterna>Brillo Y Lejía</empresaExterna>
    </consultor>

 </consultores>

 <departamentos>
    <departamento CDD="C01">
        <nombre>Contabilidad</nombre>
        <director>Alberto</director>
        <empleados>
           <empleado CED="C01"></empleado>
           <empleado CED="C02"></empleado>
           <empleado CED="C03"></empleado>
        </empleados>
        <direccion>
            <calle>Magallanes</calle>
            <ciudad>Cartagena</ciudad>
            <codigoPostal>30310</codigoPostal>
        </direccion>
    </departamento>

    <departamento CDD="L01">
        <nombre>Limpieza</nombre>
        <director>Martín</director>
        <empleados>
           <empleado CED="L01"></empleado>
           <empleado CED="L02"></empleado>
           <empleado CED="L03"></empleado>
        </empleados>
        <direccion>
            <calle>Colombia</calle>
            <ciudad>Zaragoza</ciudad>
            <codigoPostal>50001</codigoPostal>
        </direccion>
    </departamento>

    <departamento CDD="P01">
        <nombre>Producción</nombre>
        <director>Carlos</director>
        <empleados>
           <empleado CED="P01"></empleado> 
        </empleados>
        <direccion>
            <calle>JuanMiguelDeLaSantisimaTrinidad</calle>
            <ciudad>Granada</ciudad>
            <codigoPostal>18001</codigoPostal>
        </direccion>
    </departamento>

    <departamento CDD="M01">
        <nombre>Mantenimiento</nombre>
        <director>Constantino</director>
        <empleados>
           <empleado CED="M01"></empleado>
           <empleado CED="M02"></empleado>
           <empleado CED="M03"></empleado>
        </empleados>
        <direccion>
            <calle>Lavueltilla</calle>
            <ciudad>Las Palmas De Gran Canaria</ciudad>
            <codigoPostal>35001</codigoPostal>
        </direccion>
    </departamento>
 </departamentos>
</registroPersonal>
